const UNIT_TYPES = {
    tank: {
        name: 'Tank',
        domain: 'land',
        size: 10,
        speed: 1,
        maxHp: 100,
        damage: 20,
        range: 150,
        attackSpeed: 30,
        buildTime: 60,
        color: '#888',
        effectColor: '#ff0',
        cost: { mass: 100, energy: 50 },
        tier: 1
    },
    bot: {
        name: 'Bot',
        domain: 'land',
        size: 6,
        speed: 2,
        maxHp: 50,
        damage: 10,
        range: 100,
        attackSpeed: 20,
        buildTime: 30,
        color: '#aaa',
        effectColor: '#f80',
        cost: { mass: 50, energy: 25 },
        tier: 1
    },
    artillery: {
        name: 'Artillery',
        domain: 'land',
        size: 12,
        speed: 0.5,
        maxHp: 80,
        damage: 50,
        range: 300,
        attackSpeed: 60,
        buildTime: 90,
        color: '#666',
        effectColor: '#f00',
        cost: { mass: 150, energy: 100 },
        tier: 2
    },
    battleship: {
        name: 'Battleship',
        domain: 'sea',
        size: 20,
        speed: 0.8,
        maxHp: 200,
        damage: 40,
        range: 250,
        attackSpeed: 40,
        buildTime: 120,
        color: '#048',
        effectColor: '#0ff',
        cost: { mass: 200, energy: 150 },
        tier: 2
    },
    submarine: {
        name: 'Submarine',
        domain: 'sea',
        size: 15,
        speed: 1.2,
        maxHp: 120,
        damage: 30,
        range: 200,
        attackSpeed: 35,
        buildTime: 80,
        color: '#026',
        effectColor: '#088',
        cost: { mass: 120, energy: 80 },
        tier: 1
    },
    fighter: {
        name: 'Fighter',
        domain: 'air',
        size: 8,
        speed: 4,
        maxHp: 60,
        damage: 15,
        range: 150,
        attackSpeed: 15,
        buildTime: 50,
        color: '#ccc',
        effectColor: '#fff',
        cost: { mass: 80, energy: 60 },
        tier: 1
    },
    bomber: {
        name: 'Bomber',
        domain: 'air',
        size: 12,
        speed: 2,
        maxHp: 100,
        damage: 60,
        range: 100,
        attackSpeed: 50,
        buildTime: 100,
        color: '#999',
        effectColor: '#ff8',
        cost: { mass: 150, energy: 120 },
        tier: 2
    },
    gunship: {
        name: 'Gunship',
        domain: 'air',
        size: 10,
        speed: 3,
        maxHp: 80,
        damage: 25,
        range: 120,
        attackSpeed: 20,
        buildTime: 70,
        color: '#bbb',
        effectColor: '#f8f',
        cost: { mass: 100, energy: 80 },
        tier: 1
    },
    engineer: {
        name: 'Engineer',
        domain: 'land',
        size: 8,
        speed: 1.5,
        maxHp: 60,
        damage: 0,
        range: 0,
        attackSpeed: 0,
        buildTime: 40,
        color: '#0f0',
        effectColor: '#0f0',
        cost: { mass: 80, energy: 40 },
        support: true,
        tier: 1
    },
    shieldGenerator: {
        name: 'Shield Generator',
        domain: 'land',
        size: 14,
        speed: 0.7,
        maxHp: 150,
        damage: 0,
        range: 0,
        attackSpeed: 0,
        buildTime: 80,
        color: '#0ff',
        effectColor: '#0ff',
        cost: { mass: 120, energy: 200 },
        support: true,
        shields: 100,
        shieldRegen: 2,
        tier: 2
    },
    experimental: {
        name: 'Experimental',
        domain: 'land',
        size: 25,
        speed: 0.5,
        maxHp: 500,
        damage: 100,
        range: 200,
        attackSpeed: 40,
        buildTime: 300,
        color: '#f0f',
        effectColor: '#f0f',
        cost: { mass: 500, energy: 400 },
        shields: 200,
        shieldRegen: 5,
        tier: 3
    },
    commander: { // ACU definition
        name: 'Commander',
        domain: 'land',
        size: 18,
        speed: 0.6,
        maxHp: 1500,
        damage: 75,
        range: 180,
        attackSpeed: 40,
        color: '#ff0',
        effectColor: '#f0f',
        cost: { mass: 0, energy: 0 }, // Starting unit
        tier: 2.5,
        support: true,
        buildList: [], // Populated dynamically in main.js after BUILDING_TYPES is loaded
        buildRate: 1.0,
        shields: 200,
        shieldRegen: 2
    }
};

export { UNIT_TYPES };
